# Generated by Django 4.0 on 2024-04-25 08:56

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_time']},
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
